# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccb0bb1fbf2f74017b700ce4621efc24998aca6e5f9be5faf0f84d6d641beef99875d45aaff1b37247f1a171659564345b53f67d8ac17f63b70208bef0093ad4

test:
  secret_key_base: 572ae7dc620dd5ee7486cad865ea612b00de880e0ff8777ebca82ea3acf44c2ca2f0516953717aa0bda6e62318c869a2c6eba5ad031b866ee047a8f7554ca6b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
